openapi: 3.1.0
x-stoplight:
  id: 578vl7vb5w8rk
info:
  title: Multidomus
  version: '1.0'
  description: Set of API endpoints for the Multidomus app
servers:
  - url: 'https://api.multidomus.it'
paths:
  /administrator:
    get:
      summary: Get administrator details by condo id
      tags:
        - Tenant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Administrator'
              examples:
                Example 1:
                  value:
                    firstName: Harold
                    lastName: Hogan
                    role: string
                    creationDate: '2019-08-24T14:15:22Z'
                    lastUpdateDate: '2019-08-24T14:15:22Z'
                    studio: Stark Industries
                    receptionHours: Lun-Ven 8-13 14-18
                    address: 'Malibu Point, 10880'
                    emergencyPhone: string
                    email: happy@gmail.com
                    pec: user@pec-example.com
                    fax: '052123456789'
                    phoneNumbers:
                      - label: Office
                        phone: '345123456789'
                    website: www.happy.us
                    notes: I'm a good admin!
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-administrator-by-condo-id
      x-stoplight:
        id: o03lz4d48liqj
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: condoCompanyId
          required: true
          description: The UUID of the condo to get info about
      description: Retrieve the information of the administrator for the given condo
    parameters: []
  /condo:
    get:
      summary: Get condo details by condo id
      tags:
        - Tenant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Condo'
              examples:
                Example 1:
                  value:
                    name: Morgan
                    address: 'Malibu Point, 10880'
                    fiscalCode: STRTNY70E29Z404M
                    type: Condominio
                    creationDate: '2019-08-24T14:15:22Z'
                    lastUpdateDate: '2019-08-24T14:15:22Z'
                    adminActivities:
                      - startDate: '2019-08-24'
                        endDate: '2019-08-24'
                        adminCompanyId: e028496c-e766-4bb7-bb98-e5c8d13cbbac
                        type: EXTRAORDINARY
                    commonParts:
                      - ingresso
                      - giardino
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-condo-by-condo-id
      x-stoplight:
        id: e1atd327p214w
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: condoCompanyId
          required: true
          description: The UUID of the condo to get info about
      description: Retrieve the details of the given condo
    parameters: []
  /residential-units:
    get:
      summary: Get units details by condo id
      tags:
        - Tenant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Residential-Unit'
                  x-stoplight:
                    id: r1hqn6f9df50p
              examples:
                Example 1:
                  value:
                    - id: string
                      ownedFraction: 0.5
                      floor: 2
                      unitType: Appartamento
                      ownership: Usufruttuario
                      unitNumber: '10'
                      buildingSection: A
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-units-by-condo-id
      x-stoplight:
        id: 3ogu3cqwxrr4m
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: condoCompanyId
          required: true
          description: The UUID of the condo to get info about
      description: Retrieve the details of the owned residential units in the given condo
    parameters: []
  /healthz:
    get:
      summary: Healthcheck
      tags:
        - Users
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      operationId: get-healthz
      description: An health check endpoint
      security: []
      x-stoplight:
        id: afveor7b9pzfc
  /users/interventi-account:
    parameters: []
    post:
      summary: Link Interventi account (supplier)
      operationId: post-users-link-interventi-account
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: 8cumx1mynvpuz
                  format: email
                password:
                  type: string
                  x-stoplight:
                    id: zy2wu53ctlwqv
              required:
                - email
                - password
            examples:
              Example 1:
                value:
                  email: user@example.com
                  password: string
      description: Link the current user to a previous Interventi account
      x-stoplight:
        id: qdvmgr8yxfb5v
  /users/miocondominio-account:
    parameters: []
    post:
      summary: Link MioCondominio account (tenant or admin)
      operationId: post-users-link-miocondominio-account
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pid:
                  type: string
                  x-stoplight:
                    id: 8myasvj820nr1
                username:
                  type: string
                  x-stoplight:
                    id: 8cumx1mynvpuz
                password:
                  type: string
                  x-stoplight:
                    id: zy2wu53ctlwqv
              required:
                - pid
                - username
                - password
            examples:
              Example 1:
                value:
                  pid: '968'
                  username: IronMan
                  password: P3pp3rP0tt$
      description: Link the current user to a previous MioCondominio account
      x-stoplight:
        id: lt8gdxg4w171n
  /users/me:
    parameters: []
    get:
      summary: Get my user Info
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                    x-stoplight:
                      id: kmsqah29sscp5
                  firstAccess:
                    type: boolean
                    x-stoplight:
                      id: nuf67mghvx17k
                  emailRegistered:
                    type: boolean
                    x-stoplight:
                      id: y3oss61xqjmu5
                required:
                  - user
                  - firstAccess
                  - emailRegistered
              examples:
                First access:
                  value:
                    user:
                      roles: []
                    firstAccess: true
                    emailRegistered: false
                Login multi-role:
                  value:
                    user:
                      roles:
                        - type: Supplier
                          supplierCompanyId: 60e634ac-9cf5-4a73-a6b6-1e5d15116468
                          companyName: Stark Industries
                        - type: Tenant
                          condoCompanyId: 60e634ac-9cf5-4a73-a6b6-1e5d15116468
                          condoAddress: '10880 Malibu Point, 90265'
                    firstAccess: false
                    emailRegistered: true
        '401':
          description: Unauthorized
        '404':
          description: User Not Found
        '500':
          description: Internal Server Error
      operationId: get-users-me
      description: Retrieve the information of the authenticated user.
      x-stoplight:
        id: jj0v2znybs8xq
      tags:
        - Users
      security:
        - bearerAuth: []
    servers: []
  /users/personal-data/me:
    parameters: []
    get:
      summary: Get my personal data
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Personal-Data'
              examples:
                Example 1:
                  value:
                    givenName: Tony
                    familyName: Stark
                    completeName: Tony Stark
                    fiscalCode: STRTNY70E29Z404P
                    email: iron@man.us
                    pec: iron@pec-man.us
                    fax: '0521123456'
                    contacts:
                      - label: office
                        phone: '345123456789'
                      - label: personal
                        phone: '321987654321'
                    address:
                      country: United States
                      province: California
                      city: Malibu
                      address: 'Malibu Point, 15/A'
                      postalCode: '10880'
                    careOf: Stark Industries LTD
        '401':
          description: Unauthorized
        '404':
          description: User Not Found
        '500':
          description: Internal Server Error
      operationId: get-my-personal-data
      description: Retrieve the personal data of the authenticated user.
      x-stoplight:
        id: dgc0cafoqj7dr
      tags:
        - Users
      security:
        - bearerAuth: []
    servers: []
    patch:
      summary: Confirm personal data
      operationId: patch-users-personal-data-me
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Personal-Data-Patch'
              x-examples:
                Example 1:
                  givenName: string
                  familyName: string
                  fiscalCode: string
                  contacts:
                    phone: string
                    emergencyPhone: string
                    email: string
                    pec: string
                  address:
                    country: string
                    province: string
                    city: string
                    address: string
            examples:
              Complete data confirmation:
                value:
                  givenName: Tony
                  familyName: Stark
                  fiscalCode: STRTNY70E29Z404P
                  pec: iron@pec-man.us
                  fax: '0521123456'
                  contacts:
                    - label: office
                      phone: '345123456789'
                    - label: personal
                      phone: '321987654321'
                  address:
                    country: United States
                    province: California
                    city: Malibu
                    address: 'Malibu Point, 15/A'
                    postalCode: '10880'
                  careOf: Stark Industries LTD
              Partial update:
                value:
                  contacts:
                    - label: office
                      phone: '0532456789'
                    - label: mobile
                      phone: '345123456789'
                  fax: '0521123455'
      description: Confirm the personal data of the authenticated user.
      tags:
        - Users
      x-stoplight:
        id: sne2sug1bl5mg
components:
  schemas:
    Address:
      title: Address
      x-stoplight:
        id: f145aunsjiu37
      type: string
      examples:
        - 'Malibu Point, 10880'
    Admin-Activity:
      title: Admin-Activity
      x-stoplight:
        id: qc2tdjxlzjm3f
      type: object
      examples:
        - startDate: '2019-08-24'
          endDate: '2019-08-24'
          adminCompanyId: e028496c-e766-4bb7-bb98-e5c8d13cbbac
          type: EXTRAORDINARY
      required:
        - startDate
        - adminCompanyId
        - type
      properties:
        startDate:
          type: string
          x-stoplight:
            id: lavv5k642kf8j
          format: date
        endDate:
          type: string
          x-stoplight:
            id: v86efk74av1nm
          format: date
        adminCompanyId:
          type: string
          x-stoplight:
            id: kkzm3msj7rb69
          format: uuid
        type:
          type: string
          x-stoplight:
            id: gy9cyqbzyq9l6
          enum:
            - ORDINARY
            - EXTRAORDINARY
            - AUXILIARY
        bankAccount:
          $ref: '#/components/schemas/Bank-Account'
          x-stoplight:
            id: f77q4ecjbuavx
    Administrator:
      title: Administrator
      x-stoplight:
        id: t0kzx7bz7d3yj
      type: object
      examples:
        - firstName: Harold
          lastName: Hogan
          role: string
          creationDate: '2019-08-24T14:15:22Z'
          lastUpdateDate: '2019-08-24T14:15:22Z'
          studio: Stark Industries
          receptionHours: Lun-Ven 8-13 14-18
          address: 'Malibu Point, 10880'
          emergencyPhone: string
          email: happy@gmail.com
          pec: user@pec-example.com
          fax: '052123456789'
          phoneNumbers:
            - label: Office
              phone: '345123456789'
          website: www.happy.us
          notes: I'm a good admin!
      properties:
        firstName:
          type: string
          x-stoplight:
            id: j0vhfkrswcyro
        lastName:
          type: string
          x-stoplight:
            id: oqt0cgyv7t243
        role:
          type: string
          x-stoplight:
            id: 0vvcvhzvbyimd
        creationDate:
          type: string
          x-stoplight:
            id: hza6og3v3wggr
          format: date-time
        lastUpdateDate:
          type: string
          x-stoplight:
            id: rpk159qvf52gp
          format: date-time
        studio:
          type: string
          x-stoplight:
            id: 5w7wfm9o3jq15
        receptionHours:
          type: string
          x-stoplight:
            id: m2j37ue8wdmmw
        email:
          type: string
          x-stoplight:
            id: rhjo4j17fb4w1
          format: email
        pec:
          type: string
          x-stoplight:
            id: kkf3bsfrjimtl
          format: email
        emergencyPhone:
          type: string
          x-stoplight:
            id: ta21u41hjj3rs
        fax:
          type: string
          x-stoplight:
            id: 9u6m42htk5pqr
        phoneNumbers:
          x-stoplight:
            id: hsqh52owdtc33
          type: array
          items:
            $ref: '#/components/schemas/Contact'
            x-stoplight:
              id: qc831xgkzed7u
        address:
          $ref: '#/components/schemas/Address'
          x-stoplight:
            id: 84lkzpn9g7er3
        website:
          type: string
          x-stoplight:
            id: 868v4oaejiwk5
        notes:
          type: string
          x-stoplight:
            id: 0d58uik60hle7
      required:
        - firstName
        - lastName
        - creationDate
        - lastUpdateDate
        - studio
        - email
        - phoneNumbers
    Alert:
      title: Alert
      x-stoplight:
        id: 6nxftgc5uvjm0
      type: object
      examples:
        - title: Biciclette
          description: Si prega di evitare di lasciare biciclette nell'androne
          creationDate: '2019-08-24T14:15:22Z'
          type: Regolamento
      properties:
        title:
          type: string
          x-stoplight:
            id: 4yjmb7ly5vava
        description:
          type: string
          x-stoplight:
            id: fy2ildq5okt1v
        creationDate:
          type: string
          x-stoplight:
            id: u53tidut3a6cq
          format: date-time
        type:
          x-stoplight:
            id: myk55xlltrcoh
          enum:
            - Scadenza
            - Manutenzione
            - Comunicazione
            - Generale
            - Regolamento
          type: string
      required:
        - title
        - creationDate
        - type
    Bank-Account:
      title: Bank-Account
      x-stoplight:
        id: oohakjwezjkoh
      type: object
      examples:
        - number: '12341234312'
          bank: Fort Knox
          IBAN: IT5492843765923878263463
        - number: '12341234312'
          bank: Fort Knox
          IBAN: IT5492843765923878263463
          SWIFT: PRACIT31XXX
          Holder: Tony Stark
      properties:
        number:
          type: string
          x-stoplight:
            id: 4n9w6ms8gavdn
        bank:
          type: string
          x-stoplight:
            id: b4jo20te3vxlq
        IBAN:
          type: string
          x-stoplight:
            id: lfbbn7jaa1eap
        holder:
          type: string
          x-stoplight:
            id: 8vb0pgyt858qi
        SWIFT:
          type: string
          x-stoplight:
            id: 6rzf28l0n1y9j
      required:
        - number
        - bank
        - IBAN
    Complete-Address:
      type: object
      properties:
        country:
          type: string
        province:
          type: string
        city:
          type: string
        address:
          type: string
        postalCode:
          type: string
      x-examples:
        Example 1:
          country: USA
          province: California
          city: Malibu
          address: Malibu Point
          postalCode: '10880'
      examples:
        - country: Italia
          province: FE
          city: Copparo
          address: 'Via Montebello, 15'
          postalCode: '44034'
    Condo:
      title: Condo
      x-stoplight:
        id: k1tyb24qaib9l
      type: object
      examples:
        - name: Morgan
          address: 'Malibu Point, 10880'
          fiscalCode: STRTNY70E29Z404M
          type: Condominio
          creationDate: '2019-08-24T14:15:22Z'
          lastUpdateDate: '2019-08-24T14:15:22Z'
          adminActivities:
            - startDate: '2019-08-24'
              endDate: '2019-08-24'
              adminCompanyId: e028496c-e766-4bb7-bb98-e5c8d13cbbac
              type: EXTRAORDINARY
          commonParts:
            - ingresso
            - giardino
      x-internal: false
      required:
        - name
        - address
        - type
        - creationDate
        - lastUpdateDate
        - adminActivities
        - commonParts
      properties:
        name:
          type: string
          x-stoplight:
            id: f6sde9ilzw2a1
        address:
          $ref: '#/components/schemas/Address'
          x-stoplight:
            id: t2otiys3bzv5m
        fiscalCode:
          type: string
          x-stoplight:
            id: 0rqvqbk8uh4cy
        type:
          x-stoplight:
            id: oq6wqzybssogr
          enum:
            - Condominio
            - SuperCondominio
          type: string
        creationDate:
          type: string
          x-stoplight:
            id: fkduqobxlxed0
          format: date-time
        lastUpdateDate:
          type: string
          x-stoplight:
            id: go00yw4r5q2n3
          format: date-time
        adminActivities:
          type: array
          x-stoplight:
            id: sc5uqezcglcvy
          items:
            $ref: '#/components/schemas/Admin-Activity'
            x-stoplight:
              id: urfcfnhval9ma
        commonParts:
          type: array
          x-stoplight:
            id: nxx8o6ig6gubr
          items:
            x-stoplight:
              id: 5to98x70ffv2t
            type: string
    Contact:
      title: Contact
      x-stoplight:
        id: 1q9fuyc10cm21
      type: object
      examples:
        - label: Sede HQ
          phone: '345123456789'
          fax: '0521123456'
          email: user@example.com
          pec: user@example.com
      properties:
        label:
          type: string
          x-stoplight:
            id: i5mfqx6tjfa7j
        phone:
          type: string
          x-stoplight:
            id: 12afq6qakbohj
      required:
        - phone
    Residential-Unit:
      title: Residential-Unit
      x-stoplight:
        id: 9kpusdy1aihoq
      type: object
      examples:
        - id: string
          ownedFraction: 0.5
          floor: 2
          unitType: Appartamento
          ownership: Usufruttuario
          unitNumber: '10'
          buildingSection: A
      x-internal: false
      required:
        - id
        - ownedFraction
      properties:
        id:
          type: string
        ownedFraction:
          type: number
          x-stoplight:
            id: qb8xsqu4f9rin
          exclusiveMinimum: 0
          maximum: 1
          example: 0.5
          format: float
        floor:
          type: integer
          x-stoplight:
            id: 43bvjato1okbp
        unitType:
          x-stoplight:
            id: o878v7rtdk6iz
          enum:
            - Appartamento
            - Box
            - Garage
          example: Appartamento
        ownership:
          type: string
          x-stoplight:
            id: 834034k9ovsen
        buildingSection:
          type: string
          x-stoplight:
            id: hpwta5t80s2v6
        unitNumber:
          type: string
          x-stoplight:
            id: zfq0y0g4f26z5
    Role:
      title: Role
      x-stoplight:
        id: fy88rf4k1owrr
      anyOf:
        - x-stoplight:
            id: bfx1v1a5t26y5
          properties:
            type:
              x-stoplight:
                id: 4ppeqehjjm93v
              enum:
                - Supplier
              type: string
            supplierCompanyId:
              type: string
              x-stoplight:
                id: jcv8thl7kahz7
              format: uuid
            companyName:
              type: string
              x-stoplight:
                id: qxpi1suzjsdx1
          required:
            - type
            - supplierCompanyId
            - companyName
        - x-stoplight:
            id: qdgob5qhawdq0
          properties:
            type:
              x-stoplight:
                id: qim93e8mxswg5
              enum:
                - Tenant
              type: string
            condoCompanyId:
              type: string
              x-stoplight:
                id: ninbczs22urk7
              format: uuid
            condoAddress:
              $ref: '#/components/schemas/Address'
              x-stoplight:
                id: 4k25eg95p0kjf
          required:
            - type
            - condoCompanyId
            - condoAddress
        - x-stoplight:
            id: 1oymp83ebzw2y
          properties:
            type:
              type: string
              x-stoplight:
                id: 5mqdokfjc8zae
              enum:
                - Admin
            adminCompanyId:
              type: string
              x-stoplight:
                id: 5ejlgis332hya
              format: uuid
            companyName:
              type: string
              x-stoplight:
                id: khzirtqt6d97e
          required:
            - type
            - adminCompanyId
            - companyName
      examples:
        - type: Tenant
          condoCompanyId: 2c7f0822-af41-49ba-8d30-cdf65b77d960
          condoAddress: 'Malibu Point, 10880'
        - type: Supplier
          supplierCompanyId: b2e6a1c3-1a5e-44ae-a8fd-81f76fd715cf
          companyName: Multicerta s.r.l.
      type: object
    Task:
      title: Task
      x-stoplight:
        id: jt0mzq4m9dird
      type: object
      examples:
        - title: Tetto
          description: Ci sono perdite perché si è rotta una tegola del tetto
          issueDate: '2019-08-24T14:15:22Z'
          status: Nuovo
          note: la grandine ha rotto la tegola
          priority: Alta
      properties:
        title:
          type: string
          x-stoplight:
            id: j1623kzlr7sn7
        description:
          type: string
          x-stoplight:
            id: wc3b7oh0eu22b
        issueDate:
          type: string
          x-stoplight:
            id: xll5zatfitx3m
          format: date-time
        status:
          x-stoplight:
            id: gltxvf8xnfaar
          enum:
            - Nuovo
            - In corso
            - Risolto
            - Chiuso
          type: string
        note:
          type: string
          x-stoplight:
            id: ea5cz6auz04i8
        priority:
          x-stoplight:
            id: xku7hf59yvpuy
          enum:
            - Alta
            - Media
            - Bassa
          type: string
      required:
        - title
        - issueDate
        - status
        - priority
    User:
      title: User
      type: object
      x-stoplight:
        id: fugyd8ptw55o6
      examples:
        - roles:
            - type: Supplier
              supplierCompanyId: 60e634ac-9cf5-4a73-a6b6-1e5d15116468
              companyName: Stark Industries
            - type: Tenant
              condoCompanyId: 60e634ac-9cf5-4a73-a6b6-1e5d15116468
              condoAddress: '10880 Malibu Point, 90265'
      properties:
        roles:
          type: array
          x-stoplight:
            id: 6phdfbmd43rl1
          description: The roles that user can assume to operate into the app
          items:
            $ref: '#/components/schemas/Role'
            x-stoplight:
              id: usf4l3srvkcz5
      required:
        - roles
    Personal-Data:
      type: object
      x-examples:
        Example 1:
          givenName: Tony
          familyName: Stark
          fiscalCode: STRTNY70E29Z404P
          email: iron@man.us
          pec: iron@pec-man.us
          fax: '0521123456'
          contacts:
            - label: office
              phone: '345123456789'
            - label: personal
              phone: '321987654321'
          address:
            country: United States
            province: California
            city: Malibu
            address: 'Malibu Point, 10880'
      x-stoplight:
        id: cme72qiad2cuo
      x-internal: false
      examples:
        - givenName: Tony
          familyName: Stark
          completeName: Tony Stark
          fiscalCode: STRTNY70E29Z404P
          email: iron@man.us
          pec: iron@pec-man.us
          fax: '0521123456'
          contacts:
            - label: office
              phone: '345123456789'
            - label: personal
              phone: '321987654321'
          address:
            country: United States
            province: California
            city: Malibu
            address: 'Malibu Point, 15/A'
            postalCode: '10880'
          careOf: Stark Industries LTD
      required:
        - fiscalCode
        - email
        - contacts
        - address
      properties:
        givenName:
          type: string
        familyName:
          type: string
        completeName:
          type: string
          x-stoplight:
            id: 7eoin571whbyp
        fiscalCode:
          type: string
        email:
          type: string
          format: email
        pec:
          type: string
          format: email
        fax:
          type: string
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        address:
          $ref: '#/components/schemas/Complete-Address'
        careOf:
          type: string
          x-stoplight:
            id: ypwhfqzulpw52
    Personal-Data-Patch:
      type: object
      x-stoplight:
        id: n60g2663dr8et
      x-internal: false
      examples:
        - givenName: Tony
          familyName: Stark
          fiscalCode: STRTNY70E29Z404P
          pec: iron@pec-man.us
          fax: '0521123456'
          contacts:
            - label: office
              phone: '345123456789'
            - label: personal
              phone: '321987654321'
          address:
            country: United States
            province: California
            city: Malibu
            address: 'Malibu Point, 15/A'
            postalCode: '10880'
          careOf: Stark Industries LTD
      properties:
        givenName:
          type: string
        familyName:
          type: string
        fiscalCode:
          type: string
        pec:
          type: string
          format: email
        fax:
          type: string
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        address:
          $ref: '#/components/schemas/Complete-Address'
        careOf:
          type: string
      description: ''
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: The "Authorization" header must be a JWT bearer token issued by TS Identity containing the user email and the assigned TS ID in UUID format
security:
  - bearerAuth: []
tags:
  - name: Admin
  - name: Supplier
  - name: Tenant
  - name: Users
